//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Username { get; set; }
        public string Contrasena { get; set; }
        public Nullable<double> Dinero { get; set; }
        public string Nombre { get; set; }

        public bool Discount(double valor)
        {
            if (valor <= this.Dinero)
            {
                this.Dinero -= valor;
                return true;
            }
            return false;
        }

        public bool Validate(String contrasena)
        {
            if (this.Contrasena.Equals(contrasena))
            {
                return true;
            }
            return false;
        }
    }
}
